[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/imdario/mergo"
  version = "0.3.6"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/urfave/negroni"
  version = "1.0.0"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.4.0"

[[constraint]]
  name = "gotest.tools"
  version = "2.1.0"

[[constraint]]
  name = "github.com/op/go-logging"
  version = "1.0.0"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.2.0"

[[constraint]]
  name = "github.com/caarlos0/env"
  version = "3.3.0"
