[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/imdario/mergo"
  version = "0.3.6"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"
