// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package mywire

import (
	"database/sql"
	"fmt"
	"github.com/L-oris/yabb/foreign/env"
	"github.com/L-oris/yabb/foreign/template"
	"github.com/L-oris/yabb/repositories/bucketrepository"
	"github.com/L-oris/yabb/repositories/db"
	"github.com/L-oris/yabb/repositories/postrepository"
	"github.com/L-oris/yabb/router"
	"github.com/L-oris/yabb/router/controllers/postcontroller"
	"github.com/L-oris/yabb/router/controllers/rootcontroller"
	"github.com/L-oris/yabb/services/postservice"
	"net/http"
)

// Injectors from mywire.go:

func ProvideRootController() (rootcontroller.Controller, error) {
	renderer, err := ProvideTemplates()
	if err != nil {
		return rootcontroller.Controller{}, err
	}
	v, err := ProvideFileServer()
	if err != nil {
		return rootcontroller.Controller{}, err
	}
	repository, err := ProvideBucket()
	if err != nil {
		return rootcontroller.Controller{}, err
	}
	db := ProvideBlogDB()
	controller := rootcontroller.NewWire(renderer, v, repository, db)
	return controller, nil
}

func ProvidePostRepository() (*postrepository.Repository, error) {
	db := ProvideBlogDB()
	repository := postrepository.NewWire(db)
	return repository, nil
}

func ProvidePostService() (*postservice.Service, error) {
	repository, err := ProvideBucket()
	if err != nil {
		return nil, err
	}
	postrepositoryRepository, err := ProvidePostRepository()
	if err != nil {
		return nil, err
	}
	service := postservice.NewWire(repository, postrepositoryRepository)
	return service, nil
}

func ProvidePostController() (postcontroller.Controller, error) {
	renderer, err := ProvideTemplates()
	if err != nil {
		return postcontroller.Controller{}, err
	}
	service, err := ProvidePostService()
	if err != nil {
		return postcontroller.Controller{}, err
	}
	controller := postcontroller.NewWire(renderer, service)
	return controller, nil
}

func ProvideRouter() (http.Handler, error) {
	controller, err := ProvidePostController()
	if err != nil {
		return nil, err
	}
	rootcontrollerController, err := ProvideRootController()
	if err != nil {
		return nil, err
	}
	handler := router.NewWire(controller, rootcontrollerController)
	return handler, nil
}

// mywire.go:

func ProvideFileServer() (func(w http.ResponseWriter, r *http.Request, name string), error) {
	return http.ServeFile, nil
}

func ProvideBlogDB() *sql.DB {
	return db.BlogDB
}

func ProvideTemplates() (template.Renderer, error) {
	return template.Template{}, nil
}

func ProvideBucket() (*bucketrepository.Repository, error) {
	repo, err := bucketrepository.NewWire(bucketrepository.BucketName(env.Vars.BucketName))
	if err != nil {
		return nil, fmt.Errorf("could not create bucket: %s", err.Error())
	}
	return repo, nil
}
